[package]
name = "get-gmail-token"
version = "0.1.0"
authors = ["Cole Mickens <cole.mickens@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
